# Generated by Django 2.2.4 on 2019-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('is_normal', models.BooleanField(default=True, verbose_name='Normal User')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
        ),
    ]
