# Generated by Django 2.2.4 on 2019-08-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190819_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
