# Generated by Django 2.2.4 on 2019-08-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190813_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availablitiy',
            field=models.IntegerField(default=1, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ImageField(upload_to='homeshopping/media/products/', verbose_name='Product Image'),
        ),
    ]
