# Generated by Django 2.2.4 on 2019-08-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190816_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availablitiy',
            new_name='is_available',
        ),
    ]
