# Generated by Django 2.2.4 on 2019-08-16 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Review Date'),
            preserve_default=False,
        ),
    ]
