# Generated by Django 2.2.4 on 2019-08-16 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Category Banner'),
            preserve_default=False,
        ),
    ]
