# Generated by Django 2.2.4 on 2019-08-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(upload_to='banners/', verbose_name='Category Banner'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ImageField(upload_to='products/', verbose_name='Product Image'),
        ),
    ]
