# Generated by Django 2.2.4 on 2019-08-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190819_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='item_name',
        ),
    ]
