# Generated by Django 2.2.4 on 2019-08-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190826_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderby',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='date_placed',
            field=models.DateField(default='', verbose_name='Date of Order Placement'),
        ),
    ]
