# Generated by Django 2.2.4 on 2019-08-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190826_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
