# Generated by Django 2.2.4 on 2019-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190826_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderby',
            name='payment_type',
            field=models.CharField(default='Bank Transfer', max_length=20),
        ),
    ]
