# Generated by Django 2.2.4 on 2019-08-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_orderby_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderby',
            name='ordered_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
    ]
